'use client'

import React from 'react'
import { motion, useInView } from 'framer-motion'
import { useRef, useState } from 'react'
import { Stethoscope, AlertTriangle, DollarSign, Clock, MapPin, ChevronDown, ChevronUp } from 'lucide-react'

interface TimelineEntry {
  date: string
  time: string
  type: string
  event: string
  source: string
  icon: React.ElementType
  accent: string
  category: string
  isFlag?: boolean
}

const TIMELINE_ENTRIES: TimelineEntry[] = [
  {
    date: '03/12/2021',
    time: '09:14',
    type: 'Medical',
    event: 'Plaintiff presents to St. Joseph ER with acute lower back pain following collision. GCS 15. Initial vitals stable. Lumbar X-ray ordered.',
    source: 'St. Joseph ER Records, p.7',
    icon: Stethoscope,
    accent: '#1A3A6B',
    category: 'medical',
  },
  {
    date: '03/12/2021',
    time: '11:30',
    type: 'Incident',
    event: 'Police report filed. Officer Johnson notes plaintiff vehicle struck from behind at ~35 mph. Defendant cited for following too closely. Witness statement obtained from M. Chen.',
    source: 'Police Report #2021-4471, p.1-3',
    icon: AlertTriangle,
    accent: '#C45C30',
    category: 'incident',
  },
  {
    date: '03/15/2021',
    time: '14:00',
    type: 'Medical',
    event: 'MRI lumbar spine: L4-L5 disc herniation with mild nerve root compression. Recommended physical therapy 3×/week × 12 weeks. Prescribed Flexeril 10mg.',
    source: 'Radiology Report, Imaging Center Associates, p.2',
    icon: Stethoscope,
    accent: '#1A3A6B',
    category: 'medical',
  },
  {
    date: '03/22/2021',
    time: '10:00',
    type: 'Treatment',
    event: 'First physical therapy session. Initial Oswestry Disability Index: 52% (severe). Goal: reduce to <20% by week 12. Therapist: Dr. P. Marsh, DPT.',
    source: 'PT Records, Marsh Rehabilitation, p.1',
    icon: Clock,
    accent: '#2D6B31',
    category: 'treatment',
  },
  {
    date: '05/03/2021',
    time: '08:45',
    type: '⚠️ Gap',
    event: 'Treatment gap: 42-day lapse in physical therapy attendance. ⚠️ Lawline Flag: Defendant may argue failure to mitigate. Confirm reason for gap with client.',
    source: 'PT Records analysis — gap detected',
    icon: AlertTriangle,
    accent: '#B8963E',
    category: 'flag',
    isFlag: true,
  },
  {
    date: '06/18/2021',
    time: '15:30',
    type: 'Medical',
    event: 'Orthopedic consultation: Dr. R. Singh recommends L4-L5 microdiscectomy. Conservative treatment failed. Surgery scheduled for 08/02/2021. Estimated recovery: 8-12 weeks.',
    source: 'Ortho Records, Spine Associates, p.4-6',
    icon: Stethoscope,
    accent: '#1A3A6B',
    category: 'medical',
  },
  {
    date: '08/02/2021',
    time: '07:30',
    type: 'Surgery',
    event: 'L4-L5 microdiscectomy performed by Dr. Singh. Procedure: 2h 14m. Discharged 08/04/2021. Post-op: 6-week restricted activity, 4-week outpatient PT.',
    source: 'Surgical Records, Riverside Medical Center, p.11-18',
    icon: Stethoscope,
    accent: '#C45C30',
    category: 'medical',
  },
  {
    date: '11/15/2021',
    time: '14:00',
    type: 'IME',
    event: 'Defendant IME by Dr. T. Freeman: opines disc herniation "pre-existing degenerative changes." Estimated MMI in 30 days. No future treatment warranted. ⚠️ Contradicts treating physician opinion.',
    source: 'IME Report, Freeman Orthopedics, p.7-9',
    icon: AlertTriangle,
    accent: '#B8963E',
    category: 'flag',
    isFlag: true,
  },
  {
    date: '01/08/2022',
    time: '10:30',
    type: 'Financial',
    event: 'Total medical specials to date: $127,440. Lost wages (9-month disability): $41,200. Future medical (Dr. Singh estimate): $28,000. Total economic damages: $196,640.',
    source: 'Damages Summary — generated by Lawline',
    icon: DollarSign,
    accent: '#2D6B31',
    category: 'damages',
  },
]

type Category = 'all' | 'medical' | 'incident' | 'treatment' | 'flag' | 'damages'

const FILTER_TABS: { id: Category; label: string }[] = [
  { id: 'all', label: 'All Events' },
  { id: 'medical', label: 'Medical' },
  { id: 'incident', label: 'Incident' },
  { id: 'treatment', label: 'Treatment' },
  { id: 'flag', label: '⚠️ Flags' },
  { id: 'damages', label: 'Damages' },
]

export function TimelineVisualizerSection() {
  const ref = useRef<HTMLElement>(null)
  const inView = useInView(ref, { once: true, margin: '-60px' })
  const [filter, setFilter] = useState<Category>('all')
  const [expanded, setExpanded] = useState(false)

  const filtered = TIMELINE_ENTRIES.filter(e => filter === 'all' || e.category === filter)
  const visible = expanded ? filtered : filtered.slice(0, 5)

  return (
    <section
      ref={ref}
      style={{
        padding: '8rem 2rem',
        background: 'var(--color-ink)',
        position: 'relative',
        overflow: 'hidden',
      }}
    >
      {/* Subtle grid */}
      <div style={{
        position: 'absolute', inset: 0, pointerEvents: 'none',
        backgroundImage: 'linear-gradient(rgba(184,150,62,0.03) 1px, transparent 1px), linear-gradient(90deg, rgba(184,150,62,0.03) 1px, transparent 1px)',
        backgroundSize: '48px 48px',
      }} />

      <div style={{ maxWidth: '72rem', margin: '0 auto', position: 'relative' }}>

        {/* Header */}
        <motion.div
          initial={{ opacity: 0, y: 24 }}
          animate={inView ? { opacity: 1, y: 0 } : {}}
          transition={{ duration: 0.6 }}
          style={{ textAlign: 'center', marginBottom: '3rem' }}
        >
          <span style={{
            fontFamily: 'var(--font-mono)',
            fontSize: '0.6875rem',
            letterSpacing: '0.14em',
            textTransform: 'uppercase',
            color: 'rgba(184,150,62,0.8)',
            display: 'block',
            marginBottom: '1.25rem',
          }}>
            Sample Output — Personal Injury
          </span>
          <h2 style={{
            fontFamily: 'var(--font-display)',
            fontSize: 'clamp(2rem, 4vw, 3rem)',
            fontWeight: 300,
            letterSpacing: '-0.03em',
            color: 'var(--color-parchment)',
            lineHeight: 1.1,
            marginBottom: '1rem',
          }}>
            This is what a Lawline
            <br />
            <em style={{
              fontStyle: 'italic',
              background: 'linear-gradient(135deg, #D4AE58 0%, #B8963E 100%)',
              WebkitBackgroundClip: 'text',
              WebkitTextFillColor: 'transparent',
              backgroundClip: 'text',
            }}>
              timeline actually looks like
            </em>
          </h2>
          <p style={{
            fontFamily: 'var(--font-body)',
            fontSize: '0.9375rem',
            color: 'rgba(253,252,250,0.5)',
            maxWidth: '40rem',
            margin: '0 auto',
            lineHeight: 1.7,
          }}>
            Every entry is source-cited to the exact page. Lawline flags treatment gaps, contradictions, and IME disputes automatically.
          </p>
        </motion.div>

        {/* Filter tabs */}
        <motion.div
          initial={{ opacity: 0, y: 16 }}
          animate={inView ? { opacity: 1, y: 0 } : {}}
          transition={{ duration: 0.5, delay: 0.2 }}
          style={{ display: 'flex', gap: '0.5rem', flexWrap: 'wrap', marginBottom: '2rem', justifyContent: 'center' }}
        >
          {FILTER_TABS.map(tab => (
            <button
              key={tab.id}
              onClick={() => setFilter(tab.id)}
              style={{
                fontFamily: 'var(--font-mono)',
                fontSize: '0.5625rem',
                letterSpacing: '0.08em',
                textTransform: 'uppercase',
                padding: '0.35rem 0.875rem',
                borderRadius: 'var(--radius-pill)',
                border: filter === tab.id ? '1px solid rgba(184,150,62,0.6)' : '1px solid rgba(255,255,255,0.12)',
                background: filter === tab.id ? 'rgba(184,150,62,0.12)' : 'transparent',
                color: filter === tab.id ? '#D4AE58' : 'rgba(253,252,250,0.45)',
                cursor: 'pointer',
                transition: 'all 0.2s ease',
              }}
            >
              {tab.label}
            </button>
          ))}
        </motion.div>

        {/* Timeline entries */}
        <div style={{ position: 'relative' }}>
          {/* Vertical line */}
          <div style={{
            position: 'absolute',
            left: '7rem',
            top: 0,
            bottom: 0,
            width: '1px',
            background: 'linear-gradient(to bottom, transparent, rgba(184,150,62,0.25) 10%, rgba(184,150,62,0.25) 90%, transparent)',
          }} />

          <div style={{ display: 'flex', flexDirection: 'column', gap: '0.125rem' }}>
            {visible.map((entry, i) => {
              const Icon = entry.icon
              return (
                <motion.div
                  key={`${entry.date}-${i}`}
                  initial={{ opacity: 0, x: -16 }}
                  animate={inView ? { opacity: 1, x: 0 } : {}}
                  transition={{ duration: 0.4, delay: 0.3 + i * 0.07 }}
                  style={{
                    display: 'grid',
                    gridTemplateColumns: '7rem 1px 1fr',
                    gap: '0 1.5rem',
                    alignItems: 'flex-start',
                    padding: '1rem 0',
                    borderRadius: 'var(--radius-md)',
                    transition: 'background 0.2s ease',
                  }}
                >
                  {/* Date/time column */}
                  <div style={{ textAlign: 'right', paddingRight: '1.5rem', paddingTop: '0.125rem' }}>
                    <div style={{
                      fontFamily: 'var(--font-mono)',
                      fontSize: '0.5rem',
                      letterSpacing: '0.08em',
                      color: entry.isFlag ? '#D4AE58' : 'rgba(184,150,62,0.6)',
                      lineHeight: 1.4,
                    }}>
                      {entry.date}
                    </div>
                    <div style={{
                      fontFamily: 'var(--font-mono)',
                      fontSize: '0.4375rem',
                      letterSpacing: '0.06em',
                      color: 'rgba(253,252,250,0.25)',
                    }}>
                      {entry.time}
                    </div>
                  </div>

                  {/* Node */}
                  <div style={{ display: 'flex', flexDirection: 'column', alignItems: 'center', marginTop: '0.2rem' }}>
                    <div style={{
                      width: 26, height: 26,
                      borderRadius: '50%',
                      background: `${entry.accent}18`,
                      border: `1.5px solid ${entry.accent}50`,
                      display: 'flex', alignItems: 'center', justifyContent: 'center',
                      flexShrink: 0,
                    }}>
                      <Icon size={12} style={{ color: entry.accent }} />
                    </div>
                  </div>

                  {/* Content */}
                  <div style={{
                    background: entry.isFlag ? 'rgba(184,150,62,0.05)' : 'rgba(255,255,255,0.02)',
                    border: entry.isFlag ? '1px solid rgba(184,150,62,0.2)' : '1px solid rgba(255,255,255,0.06)',
                    borderRadius: 'var(--radius-md)',
                    padding: '0.875rem 1rem',
                  }}>
                    <div style={{ display: 'flex', alignItems: 'center', gap: '0.5rem', marginBottom: '0.375rem' }}>
                      <span style={{
                        fontFamily: 'var(--font-mono)',
                        fontSize: '0.4375rem',
                        letterSpacing: '0.1em',
                        textTransform: 'uppercase',
                        color: entry.accent,
                        background: `${entry.accent}18`,
                        border: `1px solid ${entry.accent}30`,
                        borderRadius: 'var(--radius-pill)',
                        padding: '0.1rem 0.5rem',
                      }}>
                        {entry.type}
                      </span>
                    </div>
                    <p style={{
                      fontFamily: 'var(--font-body)',
                      fontSize: '0.8125rem',
                      color: entry.isFlag ? 'rgba(212,174,88,0.85)' : 'rgba(253,252,250,0.7)',
                      lineHeight: 1.6,
                      margin: 0,
                      marginBottom: '0.5rem',
                    }}>
                      {entry.event}
                    </p>
                    <div style={{
                      fontFamily: 'var(--font-mono)',
                      fontSize: '0.4rem',
                      letterSpacing: '0.07em',
                      color: 'rgba(253,252,250,0.25)',
                      display: 'flex',
                      alignItems: 'center',
                      gap: '0.25rem',
                    }}>
                      <MapPin size={8} style={{ color: 'rgba(184,150,62,0.4)' }} />
                      {entry.source}
                    </div>
                  </div>
                </motion.div>
              )
            })}
          </div>
        </div>

        {/* Show more / less */}
        {filtered.length > 5 && (
          <motion.div
            initial={{ opacity: 0 }}
            animate={inView ? { opacity: 1 } : {}}
            transition={{ duration: 0.4, delay: 0.8 }}
            style={{ textAlign: 'center', marginTop: '1.5rem' }}
          >
            <button
              onClick={() => setExpanded(v => !v)}
              style={{
                fontFamily: 'var(--font-mono)',
                fontSize: '0.5625rem',
                letterSpacing: '0.1em',
                textTransform: 'uppercase',
                color: '#B8963E',
                background: 'rgba(184,150,62,0.08)',
                border: '1px solid rgba(184,150,62,0.2)',
                borderRadius: 'var(--radius-pill)',
                padding: '0.5rem 1.5rem',
                cursor: 'pointer',
                display: 'inline-flex',
                alignItems: 'center',
                gap: '0.375rem',
                transition: 'all 0.2s ease',
              }}
            >
              {expanded ? <><ChevronUp size={12} /> Show Less</> : <><ChevronDown size={12} /> Show {filtered.length - 5} More Events</>}
            </button>
          </motion.div>
        )}

        {/* Bottom callout */}
        <motion.div
          initial={{ opacity: 0, y: 16 }}
          animate={inView ? { opacity: 1, y: 0 } : {}}
          transition={{ duration: 0.5, delay: 0.9 }}
          style={{
            marginTop: '3rem',
            padding: '1.5rem 2rem',
            background: 'rgba(184,150,62,0.06)',
            border: '1px solid rgba(184,150,62,0.2)',
            borderRadius: 'var(--radius-xl)',
            display: 'flex',
            alignItems: 'center',
            justifyContent: 'space-between',
            gap: '1.5rem',
            flexWrap: 'wrap',
          }}
        >
          <div>
            <div style={{ fontFamily: 'var(--font-ui)', fontSize: '0.9375rem', fontWeight: 600, color: 'var(--color-parchment)', letterSpacing: '-0.01em', marginBottom: '0.25rem' }}>
              This timeline was generated in 42 seconds
            </div>
            <div style={{ fontFamily: 'var(--font-body)', fontSize: '0.8125rem', color: 'rgba(253,252,250,0.45)', lineHeight: 1.5 }}>
              From 847 pages of medical records, police reports, and deposition transcripts
            </div>
          </div>
          <div style={{ display: 'flex', gap: '2rem', flexShrink: 0 }}>
            {[['847', 'pages read'], ['42s', 'to output'], ['9', 'sources cited']].map(([val, label]) => (
              <div key={label} style={{ textAlign: 'center' }}>
                <div style={{ fontFamily: 'var(--font-display)', fontSize: '1.5rem', fontWeight: 400, color: '#D4AE58', letterSpacing: '-0.02em', lineHeight: 1 }}>{val}</div>
                <div style={{ fontFamily: 'var(--font-mono)', fontSize: '0.4rem', letterSpacing: '0.1em', textTransform: 'uppercase', color: 'rgba(184,150,62,0.5)', marginTop: '0.25rem' }}>{label}</div>
              </div>
            ))}
          </div>
        </motion.div>
      </div>
    </section>
  )
}
